### ISSUE TITLE
F13 etc. does not work without modifier key anymore

### ISSUE THREAD

**Issue by IFD3** [btsdev/global_hotkeys#6]
I chose this library because it had the possibility for only using F13 without modifier keys to register.
Now with the version 0.1.0 its quite a downgrade since it is not possible anymore.

Since I use this key as a virtual key mapped to my mouse there is no reason to couple it with another modifier key. Also most keyboards don't even have F keys up to F24

Exception: The key [['f13']] not a valid virtual keystroke.

**Comment by btsdev** [comment]
Can you show the bindings code you used?

Please note the bindings syntax has changed now. Are you still specifying it as a list, as it was in the old way?

In the old way, the key combination was a list, e.g. ["control", "z"]. Now it's just a string: "control + z", and you can do key chords now too (which is part of the reason for the switch to specifying the hotkeys via just a single string rather than a list).

The binding should look like this:
["f13", None, some_function, False]

Also, please check out the readme if you haven't already as it's been updated with some new details for the bindings.

**Comment by IFD3** [comment]
yeah I used:
register_hotkeys([["f13"], None, function, False])
like I said, no modifier key used so its just "f13"

**Comment by btsdev** [comment]
Yeah, you're wrapping "f13" in its own list, e.g. ["f13"]. It should just be "f13".

Here's what that call should look like now:
register_hotkeys([["f13", None, function, False]])

**Comment by IFD3** [comment]
Oh I see, I was still loading the hotkeys from a config file and then doing a split wich resulted in creating a list.
I like the new approach better.
Thanks for clarifying.

**Comment by btsdev** [comment]
Thanks! Also, I've just finished adding a new exception to clarify this issue for folks in the future. It also brought to my attention that my singular register_hotkey function needed updating, so that's fixed as a result too.

Thanks again for bringing this to my attention. version 0.1.1 will be out shortly.

**Comment by btsdev** [comment]
Also, as part of some further improvements here, I also retrofitted back in support for the old binding style, so that old scripts using this library don't break. I should have done that from the start, but, I've been moving a bit too fast the past few days I guess.
