### ISSUE TITLE
Please add support for Danish characters "æ", "ø" and "å"

### ISSUE THREAD

**Issue by Blazeflack** [btsdev/global_hotkeys#9]
Hi.

I would like to request that the Danish characters "æ", "ø" and "å" be made available as possible hotkeys.
This library is used by another project that I just started using, and I would love to be able to use these characters as hotkeys.

I know you probably won't be able to easily test this functionality out yourself, so if there is anything I can do to provide info or help you test then please let me know.

Thank you :)

**Comment by btsdev** [comment]
Hi @Blazeflack,

Unfortunately, these characters may involve composite keycodes, rather than single ones (see the keycodes.py file for reference [here](https://github.com/btsdev/global_hotkeys/blob/master/global_hotkeys/keycodes.py) -- each key just has one associated code). 

Either that, or they simply map to unique keycodes that should be reported on a Danish keyboard layout (e.g. 0xC0, 0xDE, 0xDD for 'æ', 'ø', and 'å' respectively, is my guess as to what they might be - see below).

Adding the lines for these characters into keycodes.py might work for you. Feel free to fork the project and try it.

Looking at these two sites, you may be able to determine the keycodes to map here, but it may really vary by hardware. Worth a try I guess.
https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
https://kbdlayout.info/KBDDA/virtualkeys

```
    'æ':0xC0,
    'ø':0xDE,
    'å':0xDD,
```
As I'm on a standard US keyboard, like you said, this is rather difficult for me to test. Not sure the best way for you to find the keycodes for your particular keyboard layout (I tried some examples provided by ChatGPT real quick, and didn't have much luck, and that's trying even some C++ solutions). Nonetheless, ChatGPT does seem to be able to determine the keycodes somehow.

On your keyboard however, you may be able to simply find these keycodes yourself using the following code (`pip install keyboard` so you actually have the keyboard module ready to go).

```python
import keyboard

def on_key(event):
    if event.event_type == keyboard.KEY_DOWN:
        print("Key pressed:", event.name)
        print("VK Code: 0x{:02X}".format(event.scan_code))

keyboard.on_press(on_key)

print("Press any key (Ctrl+C to exit)")

# Block until Ctrl+C is pressed
keyboard.wait('esc')
```
Just run that script and type in keys you're interested in seeing keycodes for. Ctrl+C to exit.

Again, that was just quickly pulled from ChatGPT, but seems to do the job for testing my own keyboard's keys' virtual keycodes manually.

Good luck and hope that helps. I'd be interested if that's all you needed to get it working was to simply find the correct keycodes and add them keycodes.py.

Perhaps switching it into a json file and providing an interface for manually adding in non-US keyboard keys could expand the capability of this library if that worked for you.

**Comment by Blazeflack** [comment]
Hi @btsdev,

Thank you so much for the informative answer. I tried the script you gave me, and as you suspected the keycodes did in fact vary from the keycodes that are found on the web.

Just for reference my keycodes were reported as follows:
```
æ = 0x27
ø = 0x28
å = 0x1A
```
Since it may vary depending on different keyboards and keyboard layouts, I don't want to press the issue further. I will probably just find some other keys that I am unlikely to ever use with Ctrl and Shift modifiers.

Thank you again, I am closing the ticket with this comment :)

**Comment by btsdev** [comment]
Thanks for the follow up @Blazeflack, and I'm glad you were able to find these details.

Interestingly, 0x27 and 0x28 map to the right and down arrow keys on US keyboards (I wonder if your arrow keys would map to different keycodes then...).

Anyway, maybe in the future it may be worthwhile to make it easier to edit the keycode mappings so you modify a bit easier (or at least add mappings a bit easier). For one, storing them in a JSON file may be better, rather than hardcoding them into the library's source (keycodes.py to be exact).

### At present keycodes.py has two variables: 
1) `vk_key_names` which is a dictionary mapping keynames to keycodes (which, these keynames don't have to exact or anything, it's just what's referenced in keybindings in your scripts which use this library)
2) `vk_non_modifier_codes` which is a list of keycodes not belonging to modifier keys (e.g. ctrl, alt, shift)

That said, for folks with non-US keyboard layouts, getting all the different keycodes for their particular keyboard manually would indeed be tedious. Would be neat to be able to just, auto-generate these mappings by detecting the keyboard layout programmatically (and detecting the key names automatically). Not sure that Python alone can achieve that though.

Perhaps another alternative would be for me to allow for binding directly to keycodes and not just to keynames. That might open things up for a more powerful option. (though I wonder if that would help in your case. you mentioned this library is used by another project which you're using... so maybe you don't have as much easy control over modifying that other project's source or the way it allows you to assign keybindings)

Anyway, thanks for bringing this issue to light, and best of luck with the project you're using.

**Comment by btsdev** [comment]
As per my previous idea, I added an update to allow using keycodes directly instead of keynames. I don't know if this will help you or not. See the Readme for details.

```python
# For æ (keycode 0x27)
bindings = [
    ["control + 0x27", None, print_hello, False], # 0x27 is used for the æ key.
    # further bindings go here...
]
```

* Now that I think of it, they don't have to be in hex format, but, it's safer to use hex values instead of decimal values to avoid conflicting with a single digit keyname such as "5". This avoids a conflict in the case that a keycode's value happens to be less than 10. (Anyway, "control + 39" should achieve the same result as "control + 0x27")

Also, I baked the keycode tester script from earlier into the library. Just open a python interactive shell and run: 

```python
>>> from global_hotkeys import keycode_checker
```

The project is updated on PyPI, so you can just run `pip install global-hotkeys -U` and be good to go.

Note however, that direct keycode support is for non-modifier keys, so if your keycodes are different for control, shift, alt, and super/meta/window... you'd likely need to modify this project yourself to update those keycodes. Not a great solution to have to fork off of the main repos, but it may be necessary in some users' cases.
